- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
    when: ansible_os_family == "RedHat"

  - name: Install Apache on RedHat
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache on Debian
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: Start and Enable Apache on RedHat
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"
      
  - name: Start and Enable Apache on Debian
    systemd:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
      
  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/oxer.zip
      dest: /tmp/oxer.zip

  - name: Install Unzip
    package:
      name: unzip
      state: latest

  - name: Extract Template
    unarchive:
      src: /tmp/oxer.zip
      dest: /tmp/
      remote_src: yes

  - name: Move Template file to /var/www/html
    shell: "mv /tmp/oxer-html/* /var/www/html/"
    args:
      creates: /var/www/html/about.html
      